<a href="https://colab.research.google.com/github/jenilia2786/Jeni/blob/main/SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/Churn_Modelling.csv")

In [ ]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [ ]:
X = data.drop(['RowNumber', 'CustomerId', 'Surname', 'Gender'], axis=1)
y = data['Gender']

print("Features (X) head:")
print(X.head())
print("\nTarget (y) head:")
print(y.head())

Features (X) head:
   CreditScore Geography  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619    France   42       2       0.00              1          1   
1          608     Spain   41       1   83807.86              1          0   
2          502    France   42       8  159660.80              3          1   
3          699    France   39       1       0.00              2          0   
4          850     Spain   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1  
3               0         93826.63       0  
4               1         79084.10       0  

Target (y) head:
0    Female
1    Female
2    Female
3    Female
4    Female
Name: Gender, dtype: object


In [ ]:
X = pd.get_dummies(X, columns=['Geography'], drop_first=True)

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print("Features (X) after one-hot encoding head:")
print(X.head())
print("\nTarget (y) after label encoding head:")
print(y[:5])
print("\nUnique values in encoded target y:", np.unique(y))

Features (X) after one-hot encoding head:
   CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  Geography_Spain  
0               1        101348.88       1              False            False  
1               1        112542.58       0              False             True  
2               0        113931.57       1              False            False  
3               0         93826.63       0              False            False  
4               1         79084.10       0              False             True  

Target (y) after label encoding head:
[0 0 0 0 0]

Unique valu

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8000, 11)
X_test shape: (2000, 11)
y_train shape: (8000,)
y_test shape: (2000,)


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Create an instance of the SVC classifier
classifier = SVC(random_state=42) # Added random_state for reproducibility

# 2. Train the SVC model
classifier.fit(X_train, y_train)

# 3. Make predictions on the test set
y_pred = classifier.predict(X_test)

# 4. Calculate and print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# 5. Print a classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 6. Print the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.5475

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       905
           1       0.55      1.00      0.71      1095

    accuracy                           0.55      2000
   macro avg       0.27      0.50      0.35      2000
weighted avg       0.30      0.55      0.39      2000


Confusion Matrix:
[[   0  905]
 [   0 1095]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 1. Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 2. Create an instance of the SVC classifier
classifier = SVC(random_state=42) # Added random_state for reproducibility

# 3. Train the SVC model using the scaled data
classifier.fit(X_train_scaled, y_train)

# 4. Make predictions on the scaled test set
y_pred = classifier.predict(X_test_scaled)

# 5. Calculate and print the accuracy score
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")

# 6. Print a classification report
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# 7. Print the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.5670

Classification Report:
              precision    recall  f1-score   support

           0       0.55      0.22      0.31       905
           1       0.57      0.85      0.68      1095

    accuracy                           0.57      2000
   macro avg       0.56      0.54      0.50      2000
weighted avg       0.56      0.57      0.52      2000


Confusion Matrix:
[[198 707]
 [159 936]]


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# 1. Create X_geo and y_geo
X_geo = data.drop(['RowNumber', 'CustomerId', 'Surname', 'Geography'], axis=1)
y_geo = data['Geography']

# 2. Apply one-hot encoding to the 'Gender' column in X_geo
X_geo = pd.get_dummies(X_geo, columns=['Gender'], drop_first=True)

# 3. Initialize a LabelEncoder and fit-transform y_geo
le_geo = LabelEncoder()
y_geo = le_geo.fit_transform(y_geo)

# 4. Split the preprocessed X_geo and y_geo
X_geo_train, X_geo_test, y_geo_train, y_geo_test = train_test_split(X_geo, y_geo, test_size=0.2, random_state=42)

# 5. Print the .head() of X_geo and y_geo after encoding and the shapes of the split datasets
print("Features (X_geo) after one-hot encoding head:")
print(X_geo.head())
print("\nTarget (y_geo) after label encoding head:")
print(y_geo[:5])
print("\nUnique values in encoded target y_geo:", np.unique(y_geo))

print("\nX_geo_train shape:", X_geo_train.shape)
print("X_geo_test shape:", X_geo_test.shape)
print("y_geo_train shape:", y_geo_train.shape)
print("y_geo_test shape:", y_geo_test.shape)

Features (X_geo) after one-hot encoding head:
   CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Gender_Male  
0               1        101348.88       1        False  
1               1        112542.58       0        False  
2               0        113931.57       1        False  
3               0         93826.63       0        False  
4               1         79084.10       0        False  

Target (y_geo) after label encoding head:
[0 2 0 0 2]

Unique values in encoded target y_geo: [0 1 2]

X_geo_train shape: (8000, 10)
X_geo_test shape: (2000, 10)
y_geo_train shape: (8000,)
y_geo_t

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 1. Feature Scaling for Geography classification
scaler_geo = StandardScaler()
X_geo_train_scaled = scaler_geo.fit_transform(X_geo_train)
X_geo_test_scaled = scaler_geo.transform(X_geo_test)

# 2. Create an instance of the SVC classifier for Geography
classifier_geo = SVC(random_state=42)

# 3. Train the SVC model using the scaled data
classifier_geo.fit(X_geo_train_scaled, y_geo_train)

# 4. Make predictions on the scaled test set
y_geo_pred = classifier_geo.predict(X_geo_test_scaled)

# 5. Calculate and print the accuracy score
accuracy_geo = accuracy_score(y_geo_test, y_geo_pred)
print(f"Accuracy for Geography classification: {accuracy_geo:.4f}")

# 6. Print a classification report
print("\nClassification Report for Geography classification:")
print(classification_report(y_geo_test, y_geo_pred))

# 7. Print the confusion matrix
print("\nConfusion Matrix for Geography classification:")
print(confusion_matrix(y_geo_test, y_geo_pred))

Accuracy for Geography classification: 0.5775

Classification Report for Geography classification:
              precision    recall  f1-score   support

           0       0.60      0.80      0.69      1020
           1       0.53      0.68      0.60       498
           2       0.00      0.00      0.00       482

    accuracy                           0.58      2000
   macro avg       0.38      0.49      0.43      2000
weighted avg       0.44      0.58      0.50      2000


Confusion Matrix for Geography classification:
[[817 203   0]
 [160 338   0]
 [387  95   0]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# 1. Feature Scaling for Geography classification
scaler_geo = StandardScaler()
X_geo_train_scaled = scaler_geo.fit_transform(X_geo_train)
X_geo_test_scaled = scaler_geo.transform(X_geo_test)

# 2. Create an instance of the SVC classifier for Geography with class_weight='balanced'
classifier_geo = SVC(random_state=42, class_weight='balanced')

# 3. Train the SVC model using the scaled data
classifier_geo.fit(X_geo_train_scaled, y_geo_train)

# 4. Make predictions on the scaled test set
y_geo_pred = classifier_geo.predict(X_geo_test_scaled)

# 5. Calculate and print the accuracy score
accuracy_geo = accuracy_score(y_geo_test, y_geo_pred)
print(f"Accuracy for Geography classification (with balanced class weights): {accuracy_geo:.4f}")

# 6. Print a classification report
print("\nClassification Report for Geography classification (with balanced class weights):")
print(classification_report(y_geo_test, y_geo_pred))

# 7. Print the confusion matrix
print("\nConfusion Matrix for Geography classification (with balanced class weights):")
print(confusion_matrix(y_geo_test, y_geo_pred))

Accuracy for Geography classification (with balanced class weights): 0.4510

Classification Report for Geography classification (with balanced class weights):
              precision    recall  f1-score   support

           0       0.60      0.34      0.43      1020
           1       0.48      0.78      0.59       498
           2       0.27      0.34      0.30       482

    accuracy                           0.45      2000
   macro avg       0.45      0.49      0.44      2000
weighted avg       0.49      0.45      0.44      2000


Confusion Matrix for Geography classification (with balanced class weights):
[[347 286 387]
 [ 54 389  55]
 [181 135 166]]
